### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by ColorYak** [thomas15v/NoXray#18]
NoXray does not seem to have any effect on my setup, as all the ores are still visible through the walls when an xray resource pack is enabled.

I am getting a lot of these exceptions in the log:

```
[07:39:16] [Server thread/ERROR] [Sponge]: Could not pass UnloadChunkEvent$Impl to Plugin{id=noxray, name=NoXray, version=0.3.3-beta, description=Anti-Xray, authors=[thomas15v], source=.../mods/plugins/NoXray.jar}
java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to com.thomas15v.noxray.modifications.internal.InternalWorld
        at com.thomas15v.noxray.event.ChunkEventListener.onChunkUnload(ChunkEventListener.java:13) ~[ChunkEventListener.class:?]
        at org.spongepowered.common.event.listener.UnloadChunkEventListener_ChunkEventListener_onChunkUnload41.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2227-6.0.0-BETA-2275]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:311) [SpongeModEventManager.class:1.11.2-2227-6.0.0-BETA-2275]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264) [SpongeModEventManager.class:1.11.2-2227-6.0.0-BETA-2275]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:618) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
        at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:863) [auo.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:799) [lv.class:?]
        at net.minecraft.server.MinecraftServer.redirect$onUpdateTimeLightAndEntitiesGetEntityTracker$zhj000(MinecraftServer.java:3784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

Minecraft 1.11.2
Forge 13.20.0.2228
SpongeForge 6.0.0-BETA-2275
NoXray 0.3.3-beta

Note that SpongeForge is for Forge 13.20.0.2227, but my host only has the 2228 build available.

**Comment by thomas15v** [comment]
Did you have any other errors from when the server started? Or can you simply send me the entire server.log?

**Comment by ColorYak** [comment]
Sure, here is the server log:

https://pastebin.com/NB7nv9Vr

I can see there is this error during startup:

```java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres```

The `ClassCastException`s occur after moving a few blocks.

**Comment by ColorYak** [comment]
Regarding running forge build 2227 vs 2228 I can only see the following entry in the forge changelog:

> Fix some cases where world time is not passed through the WorldProvider. (#3685)
